// biome-ignore lint/performance/noBarrelFile: module index
export {
	DEFAULT_BASE_URL,
	createPlatformClient,
	type PlatformClient,
	type PlatformClientOptions,
	type WaitForJobOptions,
} from "./client";
export { PlatformApiError } from "./error";
export { EXTRACTOR_PRESETS, type ExtractorPreset } from "../extractors/preset-names";
export type { FetchLike, FetchRequestInit, FetchResponseLike } from "./fetch";
export {
	CRAWL_SITEMAP_MODES,
	ENGINES,
	RPC_ENGINES,
	RPC_ERROR_CODES,
	RPC_FORMATS,
	RPC_WARNING_CODES,
	REGIONS,
	REQUESTED_ENGINES,
	isStoredPageStub,
	type BatchOptions,
	type ConvertOptions,
	type CrawlOptions,
	type CrawlSitemapMode,
	type DemoResult,
	type DemoScrapeOptions,
	type Engine,
	type JobRef,
	type JobResultItem,
	type JobResultsPage,
	type JobState,
	type JobStatus,
	type JobType,
	type PageError,
	type PageFailure,
	type PageResult,
	type PageSuccess,
	type PlatformRpc,
	type Region,
	type RequestedEngine,
	type RpcConvertError,
	type RpcConvertOptions,
	type RpcConvertOutcome,
	type RpcConvertResult,
	type RpcEngine,
	type RpcErrorCode,
	type RpcFormat,
	type RpcPageMetadata,
	type RpcWarning,
	type RpcWarningCode,
	type ScrapeOptions,
	type ScrapeResult,
	type StoredPageStub,
} from "./types";
