name = "webforai"
main = "src/index.ts"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]


browser = { binding = "MYBROWSER" }

[durable_objects]
bindings = [
  { name = "BROWSER", class_name = "BrowserDO" }
]

[[migrations]]
new_classes = ["BrowserDO"]
tag = "v1"