// Generated by the confidence training pipeline. Do not edit by hand.

import type { BlockModel } from "./block-model";

/** Page confidence over CONFIDENCE_FEATURE_NAMES, or `undefined` before one is trained. */
export const CONFIDENCE_MODEL: BlockModel | undefined = undefined;
