// Generated by the role-model training pipeline. Do not edit by hand.

import type { RoleModels } from "./roles";

/** One binary model per role, or `undefined` before they are trained (class/aria hints are used). */
export const ROLE_MODELS: RoleModels | undefined = undefined;
