name: ci
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: ['*']
    paths-ignore:
      - 'docs/**'
      - '.vscode/**'
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9.1.4
          run_install: true
      - run: pnpm format
      - run: pnpm lint
      - run: pnpm lint:repo
      - run: pnpm build
  test:
    name: 'Test'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9.1.4
          run_install: true
      - name: Install Playwright Browsers
        run: |
          pnpm install -w playwright
          pnpm exec playwright install chromium
          pnpm exec playwright install-deps
      - name: Run tests
        run: pnpm test